# This code snippet is a GitHub Actions workflow configuration. It specifies a step that uses the `docfx-pages` action from the `sator-imaging` repository at version `v1.7.1`. This action is likely being used to generate documentation using DocFX for a GitHub Pages site.
- name: docfx for GitHub Pages
uses: sator-imaging/docfx-pages@v1.7.1
- name: markdownlint-cli2-action
uses: DavidAnson/markdownlint-cli2-action@v19.0.0
            
            
